[package]

name = "rusty-tags"
version = "0.9.3"
authors = ["Daniel Trstenjak <daniel.trstenjak@gmail.com>"]
license = "BSD-3-Clause"
description = "Create ctags/etags for a cargo project and all of its dependencies"
repository = "https://github.com/dan-t/rusty-tags"
readme = "README.md"

[dependencies]
glob = "~0.2.11"
toml = "~0.2.0"
clap = "~2.10.0"
lazy_static = "~0.2.1"
