[package]

name = "rusty-tags"
version = "0.2.0"
authors = ["Daniel Trstenjak <daniel.trstenjak@gmail.com>"]
license = "BSD-3-Clause"
description = "Create tags for a cargo project and all of its dependencies"

[dependencies]
glob = "~0.1.1"
toml = "~0.1.4"
